# Generated by Django 5.0.1 on 2025-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
    ]
