# Generated by Django 5.0.1 on 2025-12-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_movie_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='seat_configuration',
            field=models.TextField(blank=True, default='', help_text='Custom seat config like: A-20, B-25, C-20'),
        ),
    ]
