# Generated by Django 5.0.1 on 2025-12-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_theatre_seat_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='seat_configuration',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='theatre',
            name='seats_per_row',
            field=models.IntegerField(default=10),
        ),
    ]
